version: '2'
services:
  db:
    image: deangiberson/aws-dynamodb-local
    restart: always
    ports:
      - "8001:8000"
  node:
    depends_on:
      - db
    image: node:6.7.0
    volumes:
      - "./:/usr/src/app"
    links:
      - db
    ports:
      - "8000:5000"
    restart: always
    working_dir: /usr/src/app
    command: node web.js